/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cpjd.assignments.assignment8;

import javax.swing.JFrame;

/*
 Author: Will Davies
 Date: 5/8/2018
 Assignment: #8 PackageGUI.java
 Course: comp2243-31
 Description: Collects information about 10 packages from the user and outputs some information about them, using a GUI
*/
public class PackageGUI extends javax.swing.JFrame {

    private String[] names;
    private double[] weights;
    
    /**
     * Creates new form PackageGUI
     */
    public PackageGUI() {
        initComponents();
        resetPackages();
    }

    // Adds a package to the arrays, and resizes them
    public void addPackage(String name, double weight) {
        // Resize array
        String[] names = new String[this.names.length + 1];
        double[] weights = new double[this.weights.length + 1];
        
        // Copy elements from previous arrays
        for(int i = 0; i < this.names.length; i++) {
            names[i] = this.names[i];
            weights[i] = this.weights[i];
        }
        
        // Add new element
        names[names.length - 1] = name;
        weights[names.length - 1] = weight;
        
        this.names = names;
        this.weights = weights;
    }
    
    // Generates the text to set to the UI
    public String generateOutput() {
        if(weights.length == 0) return "No pacakages in array";
        
        StringBuilder builder = new StringBuilder();
        
        for(int i = 0; i < names.length; i++) {
            builder.append("Name: ").append(names[i]).append(" Weight: ").append(String.valueOf(weights[i])).append("\n");
        }
        
        return builder.toString();
    }
    
    // Returns the index of the heaviest package
    public String getHighestPackage() {
        if(weights.length == 0) return "No pacakages in array";

        double highestWeight = weights[0];
        int index = 0;
        for(int i = 0; i < weights.length; i++) {
            if(weights[i] > highestWeight) {
                highestWeight = weights[i];
                index = 0;
            }
        }
        return "The heaviest pacakage is "+names[index]+" with a weight of "+weights[index]+".";
    }
    
    // Calculates the average weight, and compares it individually to each item
    public String getAverage() {
        if(weights.length == 0) return "No packages in array"; // prevents /0 error
        
        double avg = 0;
        for(double weight : weights) avg += weight;
        avg /= weights.length;
        
        StringBuilder builder = new StringBuilder();
        
        builder.append("Average package weight: ").append(String.valueOf(avg)).append("\n");
        
       for(int i = 0; i < weights.length; i++) {
            if(weights[i] < avg) builder.append(names[i]).append("'s weight is less than average (").append(weights[i]).append(")").append("\n");
        }

        // Output names of all packages whose weight is greater than average
        for(int i = 0; i < weights.length; i++) {
            if(weights[i] >= avg) builder.append(names[i]+"'s weight is greater than or equal to the average ("+weights[i]+")").append("\n");
        }
        return builder.toString();
    }
    
    public void resetPackages() {
        this.names = new String[0];
        this.weights = new double[0];
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        packageName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        packageWeight = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        addPackage = new javax.swing.JButton();
        output = new javax.swing.JButton();
        highest = new javax.swing.JButton();
        average = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Package GUI Program");

        jLabel2.setText("Package Name:");

        jLabel3.setText("Weight:");

        console.setColumns(20);
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        addPackage.setText("Add package");
        addPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPackageActionPerformed(evt);
            }
        });

        output.setText("Output");
        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });

        highest.setText("Highest");
        highest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highestActionPerformed(evt);
            }
        });

        average.setText("Average");
        average.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averageActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(packageName)
                            .addComponent(packageWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(average, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(highest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(output, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPackage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(packageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(packageWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPackage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(output)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(highest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(average)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(reset)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPackageActionPerformed
  
       this.addPackage(packageName.getText(), Double.parseDouble(packageWeight.getText()));
       packageName.setText("");
       packageWeight.setText("");
       console.setText(generateOutput());
    }//GEN-LAST:event_addPackageActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
        console.setText(generateOutput());
    }//GEN-LAST:event_outputActionPerformed

    private void highestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highestActionPerformed

        console.setText(getHighestPackage());
    }//GEN-LAST:event_highestActionPerformed

    private void averageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averageActionPerformed

        console.setText(getAverage());
    }//GEN-LAST:event_averageActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        resetPackages();
        console.setText("");
        
        packageName.setText("");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PackageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PackageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PackageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PackageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PackageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPackage;
    private javax.swing.JButton average;
    private javax.swing.JTextArea console;
    private javax.swing.JButton highest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton output;
    private javax.swing.JTextField packageName;
    private javax.swing.JTextField packageWeight;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
